### PR TITLE
Web interface

### PR DESCRIPTION
**Pull request by healertrix**
created new interface with better UI for vehicle navigation and control.

### CODE REVIEW

**Review by amartyanambiar — COMMENTED** [review]
Integrate with the existing flask server.

**Comment by healertrix** [comment]
updated the name of the file in order to render properly check now

**Review by amartyanambiar — CHANGES_REQUESTED** [review]
image
Mishap in CSS integration?
Please rectify and Push.

**Comment by healertrix** [comment]
hmmm looking at it

**Comment by Blake2912** [comment]
@healertrix please update on this?

**Review by Blake2912 — COMMENTED** [review]
I will check and approve

**Comment by amartyanambiar** [comment]
@healertrix  has changed it ? no new commit is visible to me in this PR .

**Comment by Blake2912** [comment]
@amartyanambiar now run and check locally I fixed the issue

**Review by amartyanambiar — CHANGES_REQUESTED** [review]
Works fine except for that the Toggle isn't working.

Actions(left,right,etc..) can be performed when toggled off.

**Comment by Blake2912** [comment]
> xcept for that the Toggle isn't working.

That toggle will be removed and a button for stop will be added it was a misunderstanding by @healertrix thinking it is used to power on the vehicle

**Comment by amartyanambiar** [comment]
> > xcept for that the Toggle isn't working.
> 
> That toggle will be removed and a button for stop will be added it was a misunderstanding by @healertrix thinking it is used to power on the vehicle

Okay do it

**Comment by Blake2912** [comment]
> > > xcept for that the Toggle isn't working.
> > 
> > 
> > That toggle will be removed and a button for stop will be added it was a misunderstanding by @healertrix thinking it is used to power on the vehicle
> 
> Okay do it

I m merging this for now I m finding issues in merging the main and this branch

**Review by Blake2912 — APPROVED** [review]
approved... will reopen the issue and will specify further requirements

**Comment by amartyanambiar** [comment]
Why did this happen? How come there were conflicts?

**Comment by Blake2912** [comment]
> Why did this happen? How come there were conflicts?

Not conflicts but the branch was not getting updated from the main branch so I have merged it to the main and updated now a new PR will be raised by @healertrix where he will be adding his changes and the flask server issue is sorted out for him...

**Comment by amartyanambiar** [comment]
> > Why did this happen? How come there were conflicts?
> 
> Not conflicts but the branch was not getting updated from the main branch so I have merged it to the main and updated now a new PR will be raised by @healertrix where he will be adding his changes and the flask server issue is sorted out for him...

is it bcos of not pulling from main earlier?

**Comment by Blake2912** [comment]
> is it bcos of not pulling from main earlier?
yes

**Pull request merged**
